name: LiquidCraft
version: 0.1.0
author: Qub1
website: http://qub1.com/
main: com.qub1.liquidcraft.LiquidCraft
commands:
    makeinfinitesource:
        description: Toggles whether the liquid block the player is looking at is an infinite source.
        usage: /makeinfinitesource